openapi: 3.0.0
info:
  title: Control Center API
  description: API for managing agents and deployments.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /agents:
    get:
      summary: List all agents
      operationId: listAgents
      responses:
        '200':
          description: A list of agents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agent'
    post:
      summary: Register a new agent
      operationId: registerAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Agent created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
        '400':
          description: Invalid request body or missing address
  /deployments:
    get:
      summary: List deployments for an agent
      operationId: listDeploymentsForAgent
      parameters:
        - name: agent_id
          in: query
          required: true
          description: ID of the agent to list deployments for
          schema:
            type: string
      responses:
        '200':
          description: A list of deployments for the specified agent
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deployment'
        '400':
          description: agent_id query parameter is required
    post:
      summary: Create a new deployment
      operationId: createDeployment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentRequest'
      responses:
        '201':
          description: Deployment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        '400':
          description: Invalid request body or missing agent_id/image_url
  /heartbeat:
    post:
      summary: Agent heartbeat
      operationId: agentHeartbeat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeartbeatRequest'
      responses:
        '200':
          description: Heartbeat received
        '400':
          description: Invalid request body
        '404':
          description: Agent not found
components:
  schemas:
    Agent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        address:
          type: string
        last_seen:
          type: string
          format: date-time
        status:
          type: string
    RegisterRequest:
      type: object
      required:
        - address
      properties:
        address:
          type: string
    Deployment:
      type: object
      properties:
        id:
          type: string
        agent_id:
          type: string
        image_url:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
    DeploymentRequest:
      type: object
      required:
        - agent_id
        - image_url
      properties:
        agent_id:
          type: string
        image_url:
          type: string
    HeartbeatRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
